server:
  port: 8082

spring:
  rabbitmq:
    addresses: ${address}
    username: ${user}
    password: ${pass}
    listener.simple.retry:
      enabled: true
      initial-interval: 5000
      max-attempts: 10
      max-interval: 30000
      multiplier: 3.0
  main.allow-bean-definition-overriding: true
queue:
  name: queue.name.poc
  exchance: exchange.poc
  routing-key: routing.key.poc
